name: 'edge'
services:
  sqlite:
    image: keinos/sqlite3
    stdin_open: true
    tty: true
    volumes:
      - ./docker/sqlite:/root/db/
  minio:
    image: minio/minio:RELEASE.2025-02-07T23-21-09Z-cpuv1
    volumes:
      - minio-data-1:/data
    command: server --console-address ":9001" /data
    ports:
      - "59000:9000"
      - "59001:9001"
    networks:
      - backend
    environment:
      MINIO_ROOT_USER: default
      MINIO_ROOT_PASSWORD: password
      MINIO_DEFAULT_BUCKETS: application
  main:
    build:
      context: ./
      target: development
      args:
        COMMIT_HASH: 'abcdef'
    command: npm run dev
    restart: always
    user: "1000:1000"
    tty: true
    stdin_open: true
    ports:
      - "4444:8787"
    volumes:
      - ./:/main
    depends_on:
      - sqlite
      - minio
  chromium:
    image: seleniarm/standalone-chromium
    restart: always
    environment:
      VNC_NO_PASSWORD: 1
    networks:
      - frontend
    ports:
      - "5444:4444"
      - "57900:7900"
    depends_on:
     - main
  firefox:
    image: selenium/standalone-firefox
    restart: always
    networks:
      - frontend
    ports:
      - "5445:4444"
      - "57901:7900"
    depends_on:
      - main
volumes: #
  minio-data-1:
  sqlite-volume:
networks:
  backend:
  frontend:
